### ISSUE TITLE
open profile link with wrong git host

### ISSUE THREAD

**Issue by ruettenm** [codecentric/merge-request-notifier#131]
![image](https://user-images.githubusercontent.com/2926623/81533692-ed92f580-9366-11ea-8170-25f2fc1b5674.png)

Unhandled Promise Rejection
Error: Invalid URL
    at file:///Applications/Merge%20Request%20Notifier.app/Contents/Resources/app.asar/dist/app.js:45:106878
    at Object.i (file:///Applications/Merge%20Request%20Notifier.app/Contents/Resources/app.asar/dist/app.js:21:555)
    at f (file:///Applications/Merge%20Request%20Notifier.app/Contents/Resources/app.asar/dist/app.js:21:698)
    at file:///Applications/Merge%20Request%20Notifier.app/Contents/Resources/app.asar/dist/app.js:21:844
    at y (file:///Applications/Merge%20Request%20Notifier.app/Contents/Resources/app.asar/dist/app.js:21:930)
    at at (file:///Applications/Merge%20Request%20Notifier.app/Contents/Resources/app.asar/dist/app.js:21:16458)
    at rt (file:///Applications/Merge%20Request%20Notifier.app/Contents/Resources/app.asar/dist/app.js:21:16268)
    at it (file:///Applications/Merge%20Request%20Notifier.app/Contents/Resources/app.asar/dist/app.js:21:16624)
    at ft (file:///Applications/Merge%20Request%20Notifier.app/Contents/Resources/app.asar/dist/app.js:21:17831)
    at R (file:///Applications/Merge%20Request%20Notifier.app/Contents/Resources/app.asar/dist/app.js:21:114616)

**Comment by ruettenm** [comment]
Will be fixed in the next release.
