### ISSUE TITLE
error on startup (version 1.8)

### ISSUE THREAD

**Issue by ruettenm** [codecentric/merge-request-notifier#139]
![image](https://user-images.githubusercontent.com/2926623/86450314-9a5f7280-bd19-11ea-9768-111d3172ecbb.png)

**Comment by ruettenm** [comment]
Uncaught Exception:
Error: Cannot open /Users/travis/build/codecentric/merge-request-notifier/node_modules/keytar/build/Release/keytar.node: Error: dlopen(/Users/travis/build/codecentric/merge-request-notifier/node_modules/keytar/build/Release/keytar.node, 1): image not found
    at Object.<anonymous> (/Applications/Merge Request Notifier.app/Contents/Resources/app.asar/dist/main.js:37:639)
    at Object.<anonymous> (/Applications/Merge Request Notifier.app/Contents/Resources/app.asar/dist/main.js:37:772)
    at n (/Applications/Merge Request Notifier.app/Contents/Resources/app.asar/dist/main.js:1:110)
    at Object.<anonymous> (/Applications/Merge Request Notifier.app/Contents/Resources/app.asar/dist/main.js:10:813)
    at n (/Applications/Merge Request Notifier.app/Contents/Resources/app.asar/dist/main.js:1:110)
    at Module.<anonymous> (/Applications/Merge Request Notifier.app/Contents/Resources/app.asar/dist/main.js:38:267339)
    at n (/Applications/Merge Request Notifier.app/Contents/Resources/app.asar/dist/main.js:1:110)
    at /Applications/Merge Request Notifier.app/Contents/Resources/app.asar/dist/main.js:1:902
    at Object.<anonymous> (/Applications/Merge Request Notifier.app/Contents/Resources/app.asar/dist/main.js:1:913)
    at Module._compile (internal/modules/cjs/loader.js:880:30)

**Comment by ruettenm** [comment]
```Uncaught Exception:
Error: Cannot open /Users/travis/build/codecentric/merge-request-notifier/node_modules/keytar/build/Release/keytar.node: Error: dlopen(/Users/travis/build/codecentric/merge-request-notifier/node_modules/keytar/build/Release/keytar.node, 1): image not found
    at Object.<anonymous> (/Applications/Merge Request Notifier.app/Contents/Resources/app.asar/dist/main.js:37:639)
    at Object.<anonymous> (/Applications/Merge Request Notifier.app/Contents/Resources/app.asar/dist/main.js:37:772)
    at n (/Applications/Merge Request Notifier.app/Contents/Resources/app.asar/dist/main.js:1:110)
    at Object.<anonymous> (/Applications/Merge Request Notifier.app/Contents/Resources/app.asar/dist/main.js:10:813)
    at n (/Applications/Merge Request Notifier.app/Contents/Resources/app.asar/dist/main.js:1:110)
    at Module.<anonymous> (/Applications/Merge Request Notifier.app/Contents/Resources/app.asar/dist/main.js:38:267339)
    at n (/Applications/Merge Request Notifier.app/Contents/Resources/app.asar/dist/main.js:1:110)
    at /Applications/Merge Request Notifier.app/Contents/Resources/app.asar/dist/main.js:1:902
    at Object.<anonymous> (/Applications/Merge Request Notifier.app/Contents/Resources/app.asar/dist/main.js:1:913)
    at Module._compile (internal/modules/cjs/loader.js:880:30)```

**Comment by ruettenm** [comment]
on local build:

```
Uncaught Exception:
Error: Cannot open /Applications/Merge Request Notifier.app/Contents/Resources/app.asar/dist/keytar.node: Error: dlopen(/var/folders/6z/2mcpzy7j55zgrgb0q546nlhr0000gn/T/.de.codecentric.ruettenm.mergeRequestNotifier.xyT3iF, 1): no suitable image found.  Did find:
	/var/folders/6z/2mcpzy7j55zgrgb0q546nlhr0000gn/T/.de.codecentric.ruettenm.mergeRequestNotifier.xyT3iF: code signature in (/var/folders/6z/2mcpzy7j55zgrgb0q546nlhr0000gn/T/.de.codecentric.ruettenm.mergeRequestNotifier.xyT3iF) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
	/var/folders/6z/2mcpzy7j55zgrgb0q546nlhr0000gn/T/.de.codecentric.ruettenm.mergeRequestNotifier.xyT3iF: stat() failed with errno=17
    at Object.<anonymous> (/Applications/Merge Request Notifier.app/Contents/Resources/app.asar/dist/main.js:37:584)
    at Object.<anonymous> (/Applications/Merge Request Notifier.app/Contents/Resources/app.asar/dist/main.js:37:622)
    at n (/Applications/Merge Request Notifier.app/Contents/Resources/app.asar/dist/main.js:1:110)
    at Object.<anonymous> (/Applications/Merge Request Notifier.app/Contents/Resources/app.asar/dist/main.js:10:813)
    at n (/Applications/Merge Request Notifier.app/Contents/Resources/app.asar/dist/main.js:1:110)
    at Module.<anonymous> (/Applications/Merge Request Notifier.app/Contents/Resources/app.asar/dist/main.js:38:267339)
    at n (/Applications/Merge Request Notifier.app/Contents/Resources/app.asar/dist/main.js:1:110)
    at /Applications/Merge Request Notifier.app/Contents/Resources/app.asar/dist/main.js:1:902
    at Object.<anonymous> (/Applications/Merge Request Notifier.app/Contents/Resources/app.asar/dist/main.js:1:913)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
```
