### ISSUE TITLE
error after "brew cask upgrade"

### ISSUE THREAD

**Issue by ruettenm** [codecentric/merge-request-notifier#154]
```
TypeError: Error processing argument at index 0, conversion failure from /Applications/Merge Request Notifier.app/Contents/Resources/app.asar/dist/main/assets/icon-light-mode-1.png
    at IpcMain.<anonymous> (/Applications/Merge Request Notifier.app/Contents/Resources/app.asar/dist/main/main.js:324:14)
    at IpcMain.emit (events.js:203:13)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3883:15)
    at WebContents.emit (events.js:203:13)
```

---

merge-request-notifier 1.8.4
Electron 7.3.2
darwin 19.6.0
Locale: de

**Comment by ruettenm** [comment]
duplicate #155
