### ISSUE TITLE
unchecking the checkbox "Shortcut to open the app" is not working

### ISSUE THREAD

**Issue by ruettenm** [codecentric/merge-request-notifier#155]
```
TypeError: Error processing argument at index 0, conversion failure from 
    at updateGlobalShortcut (/Applications/Merge Request Notifier.app/Contents/Resources/app.asar/dist/main/main.js:288:31)
    at IpcMain.<anonymous> (/Applications/Merge Request Notifier.app/Contents/Resources/app.asar/dist/main/main.js:347:5)
    at IpcMain.emit (events.js:203:13)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:3883:15)
    at WebContents.emit (events.js:203:13)
```

---

merge-request-notifier 1.8.4
Electron 7.3.2
darwin 19.6.0
Locale: de

**Comment by ruettenm** [comment]
This happens when the input for the shortcut is empty
