### ISSUE TITLE
unhandled promise rejection

### ISSUE THREAD

**Issue by ruettenm** [codecentric/merge-request-notifier#60]
```
Error: Error invoking remote method 'check-for-updates': Error: net::ERR_INTERNET_DISCONNECTED
    at electron/js2c/renderer_init.js:1204:24
```

---

merge-request-notifier 0.8.0
Electron 7.0.0
darwin 18.7.0
Locale: de

**Comment by ruettenm** [comment]
![image](https://user-images.githubusercontent.com/2926623/69099110-43db4780-0a5a-11ea-90d3-df5e82cd90a6.png)

**Comment by ruettenm** [comment]
```
Error: Error invoking remote method 'check-for-updates': Error: net::ERR_INTERNET_DISCONNECTED
    at electron/js2c/renderer_init.js:1204:24
```

---

merge-request-notifier 0.8.0
Electron 7.0.0
darwin 18.7.0
Locale: de
